#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["HERC.Telematics.Services.API.csproj", "HERC.Telematics.Services.API/"]
RUN dotnet restore "HERC.Telematics.Services.API/HERC.Telematics.Services.API.csproj"
COPY . "HERC.Telematics.Services.API/"
WORKDIR "/src/HERC.Telematics.Services.API"
RUN dotnet build "HERC.Telematics.Services.API.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "HERC.Telematics.Services.API.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "HERC.Telematics.Services.API.dll"]
